<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Backup server overview</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" type="text/css" href="css/index.css">
    </head>
    <body>
        <h1>Backup server overview</h1>
        <div class="container">
            <div class="information" >
            <br/>
    			<?php
        			$backupFolder  = '/mnt/BACKUP/VPS/rdiff-backup-data/';
        			$bytes         = disk_free_space($backupFolder);
        			$si_prefix     = array( 'B', 'KB', 'MB', 'GB', 'TB', 'EB', 'ZB', 'YB' );
        			$base          = 1024;
        			$class         = min((int)log($bytes , $base) , count($si_prefix) - 1);
        			echo 'Disk free space: '.sprintf('%1.2f' , $bytes / pow($base,$class)) . ' ' . $si_prefix[$class] . '<br />';

        			$folderContent = scandir($backupFolder);
        			$oldTime       = 0;
        			$newTime       = 0;
        			foreach ($folderContent as $file) {
        			    if (strpos($file, 'session_statistics') !== false) {
        			        $returnValue = preg_replace("/(\w+)\.(.*)\.(\w+)/", "$2", $file);
        			        $time        = strtotime($returnValue);

        			        if ($newTime < $time) {
        			            $newTime = $time;
        			            $newFile = $file;
        			        }
        			        if ($oldTime > $time) {
        			            $oldTime = $time;
        			            $oldFile = $file;
        			        } elseif ($oldTime === 0) {
        			            $oldTime = $time;
        			            $oldFile = $file;
        			        }
        			    }
        			}
        			echo 'Latest backup from: '.date("j. n. Y H:i:s", $newTime);
        			$statistic = file_get_contents($backupFolder.$newFile);
        			echo '<pre>'.$statistic.'</pre>';
        			echo 'Oldest backup from: '.date("j. n. Y H:i:s", $oldTime);
        			$statistic = file_get_contents($backupFolder.$oldFile);
        			echo '<pre>'.$statistic.'</pre>';
        			?>
        	</div>
        </div>
    </body>
</html>
